INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
INSERT INTO CustomerDB_renzhaotian_both1.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both1.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
INSERT INTO CustomerDB_renzhaotian_both2.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both2.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
INSERT INTO CustomerDB_renzhaotian_both3.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both3.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
INSERT INTO CustomerDB_renzhaotian_both4.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both4.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
INSERT INTO CustomerDB_renzhaotian_both5.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both5.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
INSERT INTO CustomerDB_renzhaotian_both6.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both6.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
INSERT INTO CustomerDB_renzhaotian_both7.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both7.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both8.ClientBuyerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both8.ClientSellerInfo SET `enterpriseId` = '109', `enabled` = 'true', `erpCode` = '9', `businessLicense` = '012345ab9';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '101', `enabled` = 'true', `erpCode` = '1', `businessLicense` = '012345ab1';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '102', `enabled` = 'true', `erpCode` = '2', `businessLicense` = '012345ab2';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '103', `enabled` = 'true', `erpCode` = '3', `businessLicense` = '012345ab3';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '104', `enabled` = 'true', `erpCode` = '4', `businessLicense` = '012345ab4';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '105', `enabled` = 'true', `erpCode` = '5', `businessLicense` = '012345ab5';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '106', `enabled` = 'true', `erpCode` = '6', `businessLicense` = '012345ab6';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '107', `enabled` = 'true', `erpCode` = '7', `businessLicense` = '012345ab7';
INSERT INTO CustomerDB_renzhaotian_both9.ClientBuyerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8', `buyerOperatorId` = '123456';
INSERT INTO CustomerDB_renzhaotian_both9.ClientSellerInfo SET `enterpriseId` = '108', `enabled` = 'true', `erpCode` = '8', `businessLicense` = '012345ab8';
